---
- name: ensure apt handles https
  apt: pkg=apt-transport-https state=latest update_cache=yes force=yes

- name: install elasticsearch gpg key
  apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present

- name: add elasticsearch deb repository
  apt_repository: repo='deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main' state=present

- name: install elasticsearch packages
  apt: pkg={{ item }} state=latest update_cache=yes force=yes
  with_items:
      - elasticsearch
  notify: restart elasticsearch
